In [4]:
## NumPy: 과학, 수치 등에 대한 통계(데이터분석)
# 고성능 수치계산을 위해 제작된 라이브러리
# 머신러닝, 딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산을 볼 수 있음. 
# 또는 대량 데이터를 다룰 때에 빠른 계산능력이 요구되어 사용되는 라이브러리 
# 다차원배열, 대용량에 적합한 사이트 

# 생성된 Numpy 확인- NumPy 핵심객체(Ndarray) 
import numpy as np
temp= np.array([1,2,3])
print(type(temp)) # numpy.ndarray

# 튜토리얼: https://numpy.org/doc/stable/user/quickstart.html

numpy.ndarray

In [29]:
# NumPy 기본문법  

# 일반적인 파이썬의 List 
data1 = [1,2,3]
data2 = [1,1,2,2,3,4]

# np.array로 배열로 변환 / .shape는 크기를 확인하는 함수 
my_array1 = np.array(data1) 
print(my_array1) # [1 2 3] List w/o comma, Splitter is whitespace, not the comma 
print(my_array1.shape) # (3,) 

my_array2 = np.array(data2) 
print(my_array2) #[1 1 2 2 3 4]
print(my_array2.shape) # (6,)

## List선언 없이 바로 np.array 사용
my_array3 = np.array([3,4,5,7]) 
print(my_array3) # [3 4 5 7]
print(my_array3.dtype) # int64 

## Data Types 참조: https://numpy.org/devdocs/user/basics/types.html

### 2차원 배열 
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
print(my_array4)
'''
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
''' 
print(my_array4.shape) # (4, 3) 형태의 크기를 가진 이차원배열 

### 3차원 배열  
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(my_array5.shape) # (2, 2, 2) 형태의 크기를 가진 3차원배열(정육면체)

##NumPy 배열 생성 및 둘러보기
# Arrange: 기본함수 중에서 Range와 조금 유사하며 더욱 쉽게 배열을 만들 수 있다. 
arrange_array = np.arange(5) #arange(start,stop) / range 내장함수와 유사 
print(arrange_array)# [0, 1, 2, 3, 4] 

arrange_array2= np.arange(1,9,3,dtype="int64") #(start,stop,step)
print(arrange_array2) # [1 4 7]
type(arrange_array2) # numpy.ndarray 
arrange_array2.dtype # dtype('int64') / 데이터타입 변경가능

















[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
[3 4 5 7]
int64
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
(4, 3)
(2, 2, 2)
[0 1 2 3 4]
[1 4 7]


dtype('int64')