In [4]:
## NumPy: 과학, 수치 등에 대한 통계(데이터분석)
# 고성능 수치계산을 위해 제작된 라이브러리
# 머신러닝, 딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산을 볼 수 있음. 
# 또는 대량 데이터를 다룰 때에 빠른 계산능력이 요구되어 사용되는 라이브러리 
# 다차원배열, 대용량에 적합한 사이트 

# 생성된 Numpy 확인- NumPy 핵심객체(Ndarray) 
import numpy as np
temp= np.array([1,2,3])
print(type(temp)) # numpy.ndarray

# 튜토리얼: https://numpy.org/doc/stable/user/quickstart.html

numpy.ndarray

In [29]:
# NumPy 기본문법  

# 일반적인 파이썬의 List 
data1 = [1,2,3]
data2 = [1,1,2,2,3,4]

# np.array로 배열로 변환 / .shape는 크기를 확인하는 함수 
my_array1 = np.array(data1) 
print(my_array1) # [1 2 3] List w/o comma, Splitter is whitespace, not the comma 
print(my_array1.shape) # (3,) 

my_array2 = np.array(data2) 
print(my_array2) #[1 1 2 2 3 4]
print(my_array2.shape) # (6,)

## List선언 없이 바로 np.array 사용
my_array3 = np.array([3,4,5,7]) 
print(my_array3) # [3 4 5 7]
print(my_array3.dtype) # int64 

## Data Types 참조: https://numpy.org/devdocs/user/basics/types.html

### 2차원 배열 
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
print(my_array4)
'''
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
''' 
print(my_array4.shape) # (4, 3) 형태의 크기를 가진 이차원배열 

### 3차원 배열  
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(my_array5.shape) # (2, 2, 2) 형태의 크기를 가진 3차원배열(정육면체)

##NumPy 배열 생성 및 둘러보기
# Arrange: 기본함수 중에서 Range와 조금 유사하며 더욱 쉽게 배열을 만들 수 있다. 
arrange_array = np.arange(5) #arange(start,stop) / range 내장함수와 유사 
print(arrange_array)# [0, 1, 2, 3, 4] 

arrange_array2= np.arange(1,9,3,dtype="int64") #(start,stop,step)
print(arrange_array2) # [1 4 7]
type(arrange_array2) # numpy.ndarray 
arrange_array2.dtype # dtype('int64') / 데이터타입 변경가능


[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
[3 4 5 7]
int64
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
(4, 3)
(2, 2, 2)
[0 1 2 3 4]
[1 4 7]


dtype('int64')

In [ ]:
## Zeroes,Ones 
# 할당하는 사이즈 배열에 0이나 1을 더욱 쉽게 입력하는 함수 
zeros_arr = np.zeros((3,2)) 
print(zeros_arr) 
print("Data Type is:", zeros_arr.dtype) #float64
print("Data Shape is:", zeros_arr.shape) #(3,2)

## Ones 
# 할당하는 사이즈 배열에 0이나 1을 더욱 쉽게 입력하는 함수 
ones_arr = np.ones((3,4),dtype="int32") 
print(ones_arr) 
print("Data Type is:", ones_arr.dtype) #int32
print("Data Shape is:", ones_arr.shape) # (3,4)

In [38]:
## Reshape
after_reshape= ones_arr.reshape(6,2)
print(after_reshape)
'''
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
'''
print("Data Shape is:", ones_arr.shape) 
# 주의사항: (3,4)는 (6,2)로 바뀌지 않았다. 조건은 항상 size가(값의 갯수 or 열x행) 동일해야한다. 

#ones_arr를 다른 사이즈로 변경해보세요(3가지) / 사이즈만 동일하다면 여러 Shape으로 변환이 가능하다.
after_reshape1 = ones_arr.reshape(1,12) 
print(after_reshape1)
after_reshape2 = ones_arr.reshape(2,6) 
print(after_reshape2)
after_reshape3 = ones_arr.reshape(3,4)
print(after_reshape3) 

# reshape()에서 -1의 의미는? 차원을 자동으로 계산한다는 의미
after_reshape4 = ones_arr.reshape(3,-1)
print(after_reshape4)



[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is: (3, 4)
[[1 1 1 1 1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [43]:
## NumPy 인덱싱과 슬라이싱  
my_array= np.arange(0,4) 
print(my_array) # [0 1 2 3] 
print("my_array의 1번째 요소, 즉 0번인 것은:", my_array[0]) # 0
print("my_array[0:3]의 실행결과", my_array[0:3]) # [0 1 2 ]
print("my_array[0]의 실행결과", my_array[0]) # [0 1 2 ]
print("my_array[:2]의 실행결과", my_array[:2]) # [0 1 ]
print("my_array[:]의 실행결과", my_array[:]) # [0 1 2 3]
print("my_array[0:-1]의 실행결과", my_array[:]) 

[0 1 2 3]
my_array의 1번째 요소, 즉 0번인 것은: 0
my_array[0:3]의 실행결과 [0 1 2]
my_array[0]의 실행결과 0
my_array[:2]의 실행결과 [0 1]
my_array[:]의 실행결과 [0 1 2 3]


In [53]:
my_array2 =np.array(
    [[2,4,6,8,10,12,14,16,18],
     [3,6,9,12,15,18,21,24,27], 
     [4,8,12,16,20,24,28,32,36], 
     [5,10,15,20,25,30,35,40,45]
      ])
print(my_array2) 
print(my_array2.shape) # (4,) 
print(my_array2[0:2,0:2]) # Row먼저 -> Column 
print(my_array2[1:3,:]) # Row 먼저 -> Columnn 



[[ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]]
(4, 9)
[[2 4]
 [3 6]]
[[ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]]


In [56]:
## NumPy 정렬: sort(), argsort() 

# np.sort(): 원본에 변화를 주지 않고 복사본을 전달함. 
height_arr = np.array([174,165,182,180,168]) 
sorted_height_arr = np.sort(height_arr)

print("Height Matrix:", height_arr)
print("np.sort() Matrix :", sorted_height_arr) 

# 내림차순 정렬
desc_sorted_height_arr = np.sort(height_arr)[::-1] 
print("np.sort()[::1] : ", desc_sorted_height_arr) # 슬라이싱을 이용한 내림차순 정렬 


Height Matrix: [174 165 182 180 168]
np.sort() Matrix : [165 168 174 180 182]
np.sort()[::1] :  [182 180 174 168 165]


In [58]:
## argsort()
# numpy.argsort() 함수는 지정된 축을 따라 데이터 인덱스의 배열을 반환하도록 
# 지정된 종류의 정렬을 사용해 입력배열에서 간접정렬을 수행함 

fives = np.array([10,5,15,20])
fives_order = fives.argsort()

print("original data :", fives) # [10 5 15 20]
print("argsort() :", fives_order)# [1 0 2 3] #인덱싱 값의 역할  
print("Ascending :", fives[fives_order]) # [5 10 15 20]

# NumPy Tutorials: https://numpy.org/learn/
# NumPy Broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html
# 숙) 같은 크기의 두 배열에 대한 연산과 서로 크기가 다른 두 배열의 연산을 공부하세요 

original data : [10  5 15 20]
argsort() : [1 0 2 3]
Ascending : [ 5 10 15 20]
